---

## no openntpd
- name: yum | Install ntp server
  yum: name=ntp state=present

- name: configure ntp server
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    mode: '0644'
    backup: yes
  notify:
    - restart ntp

- name: configure ntp daemon settings
  lineinfile:
    dest: /etc/sysconfig/ntpd
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
    backup: yes
  with_items:
    - { re: '^OPTIONS=.*', l: "OPTIONS='{{ ntpclient_opts | default('-g') }}'" }
  notify:
    - restart ntp

- name: enable and start ntp service
  service: name=ntpd state=started enabled=yes
  when: not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))

