---

- name: yum | Install ntp server
  ansible.builtin.yum:
    name: "{{ ntp_packages }}"
    state: present
  register: pkg_result
  until: pkg_result is success

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp#migrating-to-chrony_using-chrony-to-configure-ntp
- block:
    - name: configure chrony server
      ansible.builtin.template:
        src: chrony.conf
        dest: /etc/chrony.conf
        mode: '0644'
        backup: yes
      notify:
        - restart chronyd
  when: ansible_distribution_major_version|int >= 8

- block:
    - name: configure ntp server
      ansible.builtin.template:
        src: ntp.conf
        dest: /etc/ntp.conf
        mode: '0644'
        backup: yes
      notify:
        - restart ntp

    - name: configure ntp daemon settings
      ansible.builtin.lineinfile:
        dest: /etc/sysconfig/ntpd
        regexp: "{{ item.re }}"
        line: "{{ item.l }}"
        backup: yes
      with_items:
        - { re: '^OPTIONS=.*', l: "OPTIONS='{{ ntpclient_opts | default('-g') }}'" }
      notify:
        - restart ntp
  when: ansible_distribution_major_version|int < 8

- name: enable and start ntp service
  ansible.builtin.service:
    name: "{{ ntp_svc }}"
    state: started
    enabled: yes
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )
